enum types {
  EDITOR_RESET = 'EDITOR_RESET',
  EDITOR_UPDATE = 'EDITOR_UPDATE',
  EDITOR_LOADING = 'EDITOR_LOADING',
  EDITOR_ERROR = 'EDITOR_ERROR',
  COVER_UPDATE_SUCCESS = 'COVER_UPDATE_SUCCESS',
}

export { types }
