enum types {
  USER_LOADING = 'USER_LOADING',
  USER_ERROR = 'USER_ERROR',

  USER_INFO_SUCCESS = 'USER_INFO_SUCCESS',
  USER_SIGN_SUCCESS = 'USER_SIGN_SUCCESS',

  LOG_OUT = 'LOG_OUT',
}

export { types }
